---
servers:
# H01
- name: dc1-h01
  adapters:
  - mode: trunk
    switch_ports:
    - Ethernet10
    - Ethernet10
    switches:
    - dc1-lf01
    - dc1-lf02
    vlans: 10
    ethernet_segment:
      short_esi: dc01:dc01:0010
    port_channel:
      mode: active

- name: dc2-h01
  adapters:
  - mode: trunk
    switch_ports:
    - Ethernet10
    - Ethernet10
    switches:
    - dc2-lf01
    - dc2-lf02
    vlans: 10
    ethernet_segment:
      short_esi: dc02:dc02:0010
    port_channel:
      mode: active
# H02
- name: dc1-h02
  adapters:
  - mode: access
    switch_ports:
    - Ethernet9
    switches:
    - dc1-lf01
    vlans: 20

- name: dc2-h02
  adapters:
  - mode: access
    switch_ports:
    - Ethernet9
    switches:
    - dc2-lf02
    vlans: 20
